# Generated by Django 3.2.8 on 2021-12-03 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=50, unique=True)),
                ('is_opioid', models.BooleanField()),
            ],
            options={
                'db_table': 'pd_drug',
            },
        ),
        migrations.CreateModel(
            name='Prescriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('credentials', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=100)),
                ('is_opioid_prescriber', models.CharField(max_length=20)),
                ('total_prescriptions', models.IntegerField()),
            ],
            options={
                'db_table': 'pd_prescriber',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=25)),
                ('state_abbrev', models.CharField(max_length=2, unique=True)),
                ('population', models.IntegerField(default=0)),
                ('death_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pd_state',
            },
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('drug_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugapp.drug')),
                ('npi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugapp.prescriber')),
            ],
            options={
                'db_table': 'pd_prescriber_drug_triple',
            },
        ),
        migrations.AddField(
            model_name='prescriber',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugapp.state'),
        ),
    ]
