# Generated by Django 3.2.8 on 2021-12-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0002_auto_20211206_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriber',
            name='picture_path',
            field=models.ImageField(default='{{MEDIA_URL}}//photos/profile_male', upload_to='photos'),
        ),
    ]
