# Generated by Django 3.2.8 on 2021-12-07 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0002_auto_20211207_0043'),
        ('drugapp', '0004_alter_prescriber_picture_path'),
    ]

    operations = [
    ]
