# Generated by Django 3.2.8 on 2021-12-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0005_merge_20211207_0023'),
        ('drugapp', '0005_merge_20211207_0525'),
    ]

    operations = [
    ]
